# http://module-build.sourceforge.net/META-spec.html
name:         Nginx-Engine-Cookies-Resolver
version:      0.02
version_from: lib/Nginx/Engine/Cookies/Resolver.pm
installdirs:  site
requires:
  Net::DNS: 0
  Nginx::Engine: 0.05
distribution_type: module
